---
- id: org-to-markdown
  name: 'org-to-markdown'
  entry: scripts/org-to-markdown.sh
  always_run: true
  pass_filenames: false
  language: 'script'
  description: "Creates a markdown file from an org file."
  require_serial: true
