---
- id: org-to-markdown
  name: 'org-to-markdown'
  entry: hooks/org-to-markdown.sh
  files: '\.org$'
  language: 'script'
  description: "Creates a markdown file from an org file."

- id: org-to-pdf
  name: 'org-to-pdf'
  entry: hooks/org-to-pdf.sh
  files: '\.org$'
  language: 'script'
  description: "Creates a pdf file from an org file."

- id: arbitrary-command
  name: 'arbitrary-command'
  entry: hooks/arbitrary-command.sh
  pass_filenames: false
  language: 'script'
  description: "Run an arbitrary shell command."

- id: argo-lint
  name: 'argo-lint'
  entry: hooks/argo-lint.sh
  language: 'script'
  types: [yaml]
  description: "Validate manifest files for Argo Workflows"

- id: nuclei-validate
  name: 'nuclei-validate'
  entry: hooks/nuclei-validate.sh
  language: 'script'
  types: [yaml]
  description: "Validate Nuclei templates"
